server:
  port: 8080

spring:
  application:
    name: mosaic

  datasource:
    url: jdbc:h2:mem:mosaicdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console